env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  vue/require-valid-default-prop:
    - off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq:
    - error
    - smart
  func-style:
    - error
    - expression
  prefer-arrow-callback:
    - error
  no-else-return:
    - error
  no-eval:
    - error
  prefer-const:
    - error
  no-empty-function:
    - error
