stages:
  - build
  - publish

variables:
  NPM_REGISTRY: "https://registry.npmjs.org/"

default:
  image: node:20.4.0-alpine
  before_script:
    - npm config set registry $NPM_REGISTRY

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist

publish:
  stage: publish
  rules:
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish --access public
  dependencies:
    - build
